swagger: "2.0"
info:
  version: "0.0.1"
  title: Tabcorp Book Microservice App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /book:
    x-swagger-router-controller: book.controller
    get:
      operationId: getAll
      description: get the books list
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetBooksListResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    
    post:
      operationId: create
      description: add a new book to the list
      # book info to be stored
      parameters:
        - name: title
          description: Book properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Book"

      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/Book"

        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"


  /book/{id}:
    x-swagger-router-controller: book.controller
    get:
      operationId: find
      description: get a book
      
      parameters:
        - name: id
          type: number
          in: path
          required: true

      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GetBookResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

    put:
      operationId: update
      description: update a book
      
      parameters:
        - name: id
          description: Book id
          type: number
          in: path
          required: true
        - name: title
          description: Book properties
          in: body
          required: true
          schema:
            $ref: "#/definitions/Book"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

    delete:
      operationId: destroy
      description: delete a book
      parameters:
        - name: id
          description: Book id
          type: number
          in: path
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse" 

  /:
    x-swagger-pipe: swagger_raw

definitions:
  # GET /book successful response
  GetBooksListResponse:
    required:
      - books
    properties:
      # The array of books
      books:
        type: array
        items: 
          type: object
          properties:
            id:
              type: number
            title:
              type: string
            category:
              type: string
            description:
              type: string

  GetBookResponse:
    required:
      - id
      - title
      - category
      - description
    properties:
      id:
        type: number
      title:
        type: string
      category:
        type: string
      description:
        type: string

  Book:
    type: object
    properties:
      id:
        type: number
      title:
        type: string
        description: Book Title
      category:
        type: string
        description: Book category
      description:
        type: string
        description: Book description
    required:
      - title
      - category

  GeneralResponse:
    type: object
    properties:
      success:
        type: number
        description: returns 1 if successful
      description:
        type: string
        description: a short comment 
    required:
      - success
      - description

  ErrorResponse:
    required:
      - message
    properties:
      code:
        type: number
      message:
        type: string
      type:
        type: string
